---
- name: Enable and start swift services.
  service:
    name:    '{{ item }}'
    state:   started
    enabled: yes
  with_items:
    - openstack-swift-account.service
    - openstack-swift-account-auditor.service
    - openstack-swift-account-reaper.service
    - openstack-swift-account-replicator.service
    - openstack-swift-container.service
    - openstack-swift-container-auditor.service
    - openstack-swift-container-replicator.service
    - openstack-swift-container-updater.service
    - openstack-swift-object.service
    - openstack-swift-object-auditor.service
    - openstack-swift-object-replicator.service
    - openstack-swift-object-updater.service
